### ISSUE TITLE
Listen Events Api

### ISSUE THREAD

**Issue by wireless90** [iotaledger/iota-sdk-native-bindings#3]
Hi guys thanks for the bindings!

I have a few issues.

1. The listen_wallet was not working for me, seems like IotaSDK WalletEventType can only be deserialized from int. Needs some tweaking.

2. Is it possible to point it to develop branch.

3. Will IF periodically compile this native bindings as iotasdk updates? Or is it better to fork it. Currently i am forking it but it best if IF code is the trusted source.

**Comment by lmoe** [comment]
Hey @wireless90

Thanks for your interest! Really happy to see .NET getting put into the mix.  :) 

1) The native bindings were initially written for the wasp-cli and we did not need to listen to events. I did add the function for it, but it was never tested properly because of it. This should have been documented better considering the library is open for everyone, sorry about that. However, besides this function everything else should be working fine. If not, that's definitely a bug.

-> I will take a look into listen_wallet and fix the remaining issues there.

2) I did consider targeting develop directly, but as there was and is a lot of activity on the sdks dev branch, I wanted to make sure I target a stable commit which I have tested properly in combination with these bindings. It has been a while and it's time for an update though. 

-> I think it's worth a try and will change it.

3) If we target develop, periodic releases make sense. I'll set it up soon.

**Comment by wireless90** [comment]
Thanks a lot. So far all utilities and Wallet/account stuffs working great! Yes listen_wallet i find it important for the sdk would be great if fixed. As rust code is alien to me, i was relying on chatgpt to do an interim fix. 😄

**Comment by lmoe** [comment]
@wireless90 Hey there, sorry for the delay! I have my challenges with Rust as well. :D 

Is it too much to ask you to try out the new feature branch `fix_listen_wallet_sdk_update` and test listen_wallet out? The wrapper now also points directly towards `develop`.

It works fine for me now. You should be able to subscribe to each wanted event via a simple JSON array of event numbers: `[0,1,2,3,4,5]` should give you access to all events. 

The current events are:

```
    /** Consolidation is required. */
    ConsolidationRequired = 0,
    /** Nano Ledger has generated an address. */
    LedgerAddressGeneration = 1,
    /** A new output was created. */
    NewOutput = 2,
    /** An output was spent. */
    SpentOutput = 3,
    /** A transaction was included into the ledger. */
    TransactionInclusion = 4,
    /** A progress update while submitting a transaction. */
    TransactionProgress = 5,
``` 

You need to invoke `listen_wallet` with the following args:

1. The already established wallet pointer
2. A pointer to the event id JSON array 
3. A callback with one string pointer arg

Depending on the DllImport configuration you most likely can just pass the string and callback without marshalling to IntPtrs. 

The callback once called will receive the event as a null terminated JSON string pointer.
You need to copy it into your memory space and call the sdks `destroy_string` function on the passed argument afterwords to delete it in the SDKs memory region.

Not sure how you implement it on the C# side, but this should hopefully explain it. 

```csharp
var cb = (IntPtr eventResponse) => {
  var copiedResponse = Marshal.PtrToStringAuto(eventResponse);
  var parsedEvent = JsonConvert.Deserialize<EventType>(copiedResponse);
  sdk.DestroyString(eventResponse);

  // Do something with parsedEvent
}

var eventIds = "[0,1,2,3,4,5]";
sdk.ListenWallet(walletPtr, eventIds, cb);
```

As an example, a full LedgerAddressGeneration event will look like this:
`{"accountIndex":0,"event":{"type":1,"address":"smr1qq4qz2h9123123123132123123123123"}}`

So you can simply match the deserialize type by matching `event.type`.

**Comment by lmoe** [comment]
@wireless90 fyi: I've ran a new release which includes the newest iota-sdk develop at commit `cd3345a7` and contains the listen_wallet changes too.

**Comment by wireless90** [comment]
@lmoe thank you! will integrate it into the .net bindings and try it out

**Comment by wireless90** [comment]
@lmoe , have integrated the new dlls and its working well. Thank you.
